spring.application.name=Book-and-Loaning-Management-System
spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=admin
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update